### ISSUE TITLE
set_heading()

### ISSUE THREAD

**Issue by AGenews** [karol-szuster/kulka#1]
Dear karol-szuster,
thank you for the kulka rep!
I just forked this rep and have added a set_heading(angle) command according to your set_back_led function and the faulkner pysphero rep. 
I know that I would have to send a uint_16 for the angle but I don't really understand what '!BHB' , '!H', '!B! stand for in your request function ..... Could you please explain that? I've already tried to send tha angle as '!H' but even with explicitly turning on the stabilization the Sphero does not turn while standing still.
Thanks a lot!
Best AGenews

**Comment by karol-szuster** [comment]
Hello,

All those B, H and other magic symbols are explained here: https://docs.python.org/3/library/struct.html

I've implemented set_heading function but unfortunately I'm unable to perform any real world testing because I don't have Sphero anymore.

**Comment by AGenews** [comment]
Dear karol,
thank you for your reply! I think that the set:heading works anyhow differently than I thought and always net to have a roll(0,0) followed.
Thanks a lot,
Best,
agenews
