### ISSUE TITLE
TypeError: (function) takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by s3594077** [karol-szuster/kulka#2]
the flag attribute in baseconnection.py line 30
(written += wlist[0].send(data[written:], flag)
causes an python error:
TypeError: (function) takes exactly 2 arguments (3 given)

you can delete flag from send function to fix the problem :)

**Comment by karol-szuster** [comment]
Actually this never happened to me and according to python documentation 'flag' attribute is perfectly fine. Can you please provide some more details about your operating system, python version and pybluez version?

**Comment by s3594077** [comment]
Sure. 

Operating System:
Windows 10 Pro, 64 Bit AMD Phenom II x6 Processor

Python Version:
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32

The created Error Message:
Traceback (most recent call last):
  File "random_movement.py", line 21, in <module>
    main()
  File "random_movement.py", line 11, in main
    kulka.set_inactivity_timeout(3600)
  File "C:\Python27\lib\site-packages\kulka\core\core.py", line 53, in set_inactivity_timeout
    return self._send(request.SetInactivityTimeout(timeout))
  File "C:\Python27\lib\site-packages\kulka\core\core.py", line 32, in _send
    self._connection.send(request_.tobytes())
  File "C:\Python27\lib\site-packages\kulka\connection\baseconnection.py", line 30, in send
    written += wlist[0].send(data[written:], flags)
TypeError: send() takes exactly 2 arguments (3 given)

If I remove "flags" from line 30 in baseconnection.py the error is fixed.
Nice work by the way! Are there any plans on incorporating collision detection into your python api?

**Comment by karol-szuster** [comment]
I've never tried this library on Windows, nice to know that it runs with only one small issue ;)
It looks like bluez for windows and for linux differs a bit but I think hence the flags argument is not used anyway so I will just remove it instead of bothering with bluez quirks ;)

Regarding your second question about collision detection - currently I'm not planning to implement any new functionalities.
