### ISSUE TITLE
Sphero Heading

### ISSUE THREAD

**Issue by ChristianTiel2108** [karol-szuster/kulka#3]
Is there anyway to change the heading with the kulka library?

**Comment by karol-szuster** [comment]
Something like this?

`with Kulka('01:02:03:04:05:06') as kulka:
    kulka.set_heading(0)`

**Comment by ChristianTiel2108** [comment]
Would I need to import anything else from the kulka library besides Kulka? I ask this because when I run that code I am given a traceback error.

**Comment by ChristianTiel2108** [comment]
Never mind, I have figured it out. The version I got after running 'pip install kulka' was missing all the necessary files for setting the heading. So I just used your version to create new files in my version and now it is working.
