### ISSUE TITLE
kulka won't install on macos sierra

### ISSUE THREAD

**Issue by timrichardson** [karol-szuster/kulka#4]
sudo pip install kulka
in a python 3.5 virtual env on osx sierra:
`  Running setup.py bdist_wheel for pybluez ... error`
...
`/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/System/Library/Frameworks/IOBluetooth.framework/Headers -I/System/Library/Frameworks/CoreFoundation.framework/Headers -I/opt/local/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c osx/_osxbt.c -o build/temp.macosx-10.12-x86_64-3.5/osx/_osxbt.o
  osx/_osxbt.c:676:5: error: unknown type name 'IOBluetoothDeviceInquiryRef'; did you mean 'IOBluetoothDeviceRef'?
`

**Comment by Chaddai** [comment]
Given the error and the fact that kulka is pure python code, I believe this error is coming from pybluez installation (pybluez use the bluez C library to allow bluetooth use through Python, kulka is just one of the library that make use of this facility).
You'll probably have more luck posting this issue in pybluez repository (if it hasn't already been done, and maybe resolved !).

**Comment by karol-szuster** [comment]
Yes, @Chaddai is right. It's not a problem with this library but with one of its dependencies (pybluez to be specific) and you will probably have more luck if you ask pybluez developers for help.
